export const GET_USERS = 'GET_USERS';
export const CREATE_BUY_ORDER = 'CREATE_BUY_ORDER';
export const CREATE_SELL_ORDER = 'CALCULATE_FUEL_SAVINGS';
export const DELETE_ORDER = 'CALCULATE_FUEL_SAVINGS';
